---
- name: Install php-fpm and deps
  apt:
    name:
      - php7.2
      - php7.2-fpm
      - php7.2-common
      - php7.2-mbstring
      - php7.2-bcmath
      - php7.2-mysql
      - php7.2-gd
      - php7.2-json
      - php7.2-xml
      - php7.2-curl
      - php7.2-zip
      - php-apcu
      - php-redis
    state: present
  notify: restart php-fpm

- name: Install composer
  apt:
    name: composer
    state: present
