easy_admin:
    site_name: nsfwdiscordme
    design:
        brand_color: '#2e365a'
        form_theme: 'admin/form/bootstrap_4.html.twig'
        assets:
            css:
                - 'build/css/admin.css'
            js:
                - 'build/js/admin.js'
    entities:
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - name
            form:
                fields:
                    - name

        Server:
            class: App\Entity\Server
            list:
                fields:
                    - id
                    - isEnabled
                    - { property: 'iconMedia', label: 'Icon', template: 'admin/fields/media.html.twig', type: 'entity' }
                    - name
                    - { property: 'slug', label: 'Slug', template: 'admin/fields/slug.html.twig' }
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - summary
            form:
                fields:
                    - name
                    - slug
                    - { property: 'discordID', label: 'Discord ID', type: 'text' }
                    - user
                    - summary
                    - description
                    - { property: 'categories', type: 'entity' }
                    - { property: 'iconMedia', type: 'file', type_options: { data_class: null, mapped: false } }
                    - { property: 'botInviteChannelID', label: 'Bot invite channel ID' }
                    - bumpPoints
                    - dateNextBump
                    - dateCreated
                    - dateUpdated
                    - botHumanCheck
                    - isEnabled
                    - isPublic
                    - isActive


        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - discordEmail
                    - discordUsername
                    - discordDiscriminator

        Media:
            class: App\Entity\Media
            list:
                fields:
                    - id
                    - path
                    - name
                    - adapter
                    - dateCreated
