easy_admin:
    site_name: nsfwdiscordme
    user:
        avatar_property_path: 'getDiscordAvatarURL'
    design:
        brand_color: '#2e365a'
        form_theme: 'admin/form/bootstrap_4.html.twig'
        assets:
            css:
                - 'build/css/admin.css'
            js:
                - 'build/js/admin.js'
        menu:
            - { entity: Server, label: 'Servers', icon: 'server' }
            - { entity: User, label: 'Users', icon: 'user' }
            - { entity: ServerTeamMember, label: 'Team Members', icon: 'users' }
            - { entity: Media, label: 'Media', icon: 'image' }
            - { entity: Category, label: 'Categories', icon: 'tags' }
            - { entity: BannedServer, label: 'Banned Servers', icon: 'ban' }
            - { entity: BannedUser, label: 'Banned Users', icon: 'ban' }
            - { entity: BannedWord, label: 'Banned Words', icon: 'ban' }
    entities:
        Server:
            class: App\Entity\Server
            list:
                fields:
                    - id
                    - isEnabled
                    - { property: 'iconMedia', label: 'Icon', template: 'admin/fields/media.html.twig', type: 'entity' }
                    - name
                    - { property: 'slug', label: 'Slug', template: 'admin/fields/slug.html.twig' }
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - dateCreated
            form:
                fields:
                    - name
                    - slug
                    - { property: 'discordID', label: 'Discord ID', type: 'text' }
                    - user
                    - bumpPoints
                    - { property: 'premiumStatus', type: 'choice', type_options: { choices: { Standard: 0, Gold: 1, Platinum: 2, Master: 3 }}}
                    - summary
                    - description
                    - { property: 'categories', type: 'entity' }
                    - { property: 'iconMedia', type: 'file', type_options: { data_class: null, mapped: false } }
                    - { property: 'bannerMedia', type: 'file', type_options: { data_class: null, mapped: false } }
                    - { property: 'botInviteChannelID', label: 'Bot invite channel ID' }
                    - botHumanCheck
                    - isEnabled
                    - isPublic
                    - isActive
                    - teamMembers

        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - isEnabled
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - { property: 'discordEmail', label: 'Email' }
                    - { property: 'discordUsername', label: 'Username' }
                    - { property: 'discordDiscriminator', label: 'Discriminator' }
                    - dateCreated
                    - dateLastLogin
            form:
                fields:
                    - { property: 'discordID', label: 'Discord ID', type: 'text' }
                    - discordUsername
                    - discordDiscriminator
                    - discordEmail
                    - discordAvatar

        ServerTeamMember:
            class: App\Entity\ServerTeamMember
            list:
                fields:
                    - id
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - discordUsername
                    - discordDiscriminator
                    - role

        Media:
            class: App\Entity\Media
            list:
                fields:
                    - id
                    - { property: 'path', template: 'admin/fields/media.html.twig' }
                    - name
                    - adapter
                    - dateCreated
            form:
                fields:
                    - path
                    - name
                    - adapter

        Category:
            class: App\Entity\Category
            list:
                fields:
                    - name
                    - slug
            form:
                fields:
                    - name
                    - slug

        BannedServer:
            class: App\Entity\BannedServer

        BannedUser:
            class: App\Entity\BannedUser

        BannedWord:
            class: App\Entity\BannedWord
