easy_admin:
    site_name: nsfwdiscordme
    design:
        brand_color: '#2e365a'
        form_theme: 'admin/form/bootstrap_4.html.twig'
        assets:
            css:
                - 'build/css/admin.css'
            js:
                - 'build/js/admin.js'
    entities:
        Server:
            label: Servers
            class: App\Entity\Server
            list:
                fields:
                    - id
                    - isEnabled
                    - { property: 'iconMedia', label: 'Icon', template: 'admin/fields/media.html.twig', type: 'entity' }
                    - name
                    - { property: 'slug', label: 'Slug', template: 'admin/fields/slug.html.twig' }
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - dateCreated
            form:
                fields:
                    - name
                    - slug
                    - { property: 'discordID', label: 'Discord ID', type: 'text' }
                    - user
                    - bumpPoints
                    - { property: 'premiumStatus', type: 'choice', type_options: { choices: { Standard: 0, Gold: 1, Platinum: 2, Master: 3 }}}
                    - summary
                    - description
                    - { property: 'categories', type: 'entity' }
                    - { property: 'iconMedia', type: 'file', type_options: { data_class: null, mapped: false } }
                    - { property: 'bannerMedia', type: 'file', type_options: { data_class: null, mapped: false } }
                    - { property: 'botInviteChannelID', label: 'Bot invite channel ID' }
                    - botHumanCheck
                    - isEnabled
                    - isPublic
                    - isActive
                    - teamMembers

        User:
            label: Users
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - discordEmail
                    - discordUsername
                    - discordDiscriminator
                    - dateCreated
            form:
                fields:
                    - { property: 'discordID', label: 'Discord ID', type: 'text' }
                    - discordUsername
                    - discordDiscriminator
                    - discordEmail
                    - discordAvatar
                    - roles

        ServerTeamMember:
            label: Team Members
            class: App\Entity\ServerTeamMember
            list:
                fields:
                    - id
                    - { property: 'discordID', label: 'Discord ID', type: 'string' }
                    - discordUsername
                    - discordDiscriminator
                    - role

        Media:
            class: App\Entity\Media
            list:
                fields:
                    - id
                    - { property: 'path', template: 'admin/fields/media.html.twig' }
                    - name
                    - adapter
                    - dateCreated
            form:
                fields:
                    - path
                    - name
                    - adapter

        Category:
            label: Categories
            class: App\Entity\Category
            list:
                fields:
                    - name
                    - slug
            form:
                fields:
                    - name
                    - slug

        BannedServer:
            label: Banned Servers
            class: App\Entity\BannedServer

        BannedUser:
            label: Banned Users
            class: App\Entity\BannedUser

        BannedWord:
            label: Banned Words
            class: App\Entity\BannedWord
