# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(ELASTICSEARCH_HOST)%', port: '%env(int:ELASTICSEARCH_PORT)%' }
    indexes:
        app:
            types:
                server:
                    indexable_callback: ['App\Storage\Elastica\ServerIndexableChecker', 'isIndexable']
                    properties:
                        name: ~
                        summary: ~
                        description: ~
                        categories: ~
                        tags: ~
                        bumpPoints: { fielddata: true }
                        membersOnline: { fielddata: true }
                        premiumStatus: { fielddata: true }
                    persistence:
                        driver: orm
                        model: App\Entity\Server
                        provider: ~
                        finder: ~
        events:
            types:
                event:
                    properties:
                        server: ~
                        eventType: ~
                        dateCreated:
                            type: date
                    persistence:
                        driver: orm
                        model: App\Entity\ServerEvent
                        provider: ~
                        finder: ~
                        listener:
                            insert: true
