imports:
    - { resource: version.yaml }

framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true

    session:
        handler_id: App\Storage\Sessions\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800
        gc_maxlifetime: 604800

    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']

    assets:
        version: '%git_commit%'
        version_format: '%%s?version=%%s'
