security:
    encoders:
        App\Security\UserProvider: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_users:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: app_users
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/profile,      role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/server,       role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api/bump/,    role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api/server/,  role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin/login,  role: ROLE_ADMIN }
        - { path: ^/admin/code,   role: ROLE_ADMIN }
        - { path: ^/admin/,       role: ROLE_SUPER_ADMIN }
