# Routes must be imported explicitly to ensure ServerController, which
# includes a "catch all" route, gets loaded last.
home:
    resource: ../../src/Controller/HomeController.php
    type: annotation
profile:
    resource: ../../src/Controller/ProfileController.php
    type: annotation
auth:
    resource: ../../src/Controller/AuthController.php
    type: annotation
search:
    resource: ../../src/Controller/SearchController.php
    type: annotation
upgrade:
    resource: ../../src/Controller/UpgradeController.php
    type: annotation
category:
    resource: ../../src/Controller/CategoryController.php
    type: annotation
contact:
    resource: ../../src/Controller/ContactController.php
    type: annotation
api:
    resource: ../../src/Controller/ApiController.php
    type: annotation
server:
    resource: ../../src/Controller/ServerController.php
    type: annotation
