parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'

    App\Storage\Sessions\RedisSessionHandler:
        arguments:
            - '@Redis'
            - { prefix: 'session_', database: 0 }

    App\Discord\Discord:
        class: App\Discord\Discord
        arguments:
            - '@Symfony\Component\Cache\Adapter\AdapterInterface'
            - '%env(DISCORD_CLIENT_ID)%'
            - '%env(DISCORD_CLIENT_SECRET)%'
            - '%env(DISCORD_BOT_TOKEN)%'

    RestCord\DiscordClient:
        class: RestCord\DiscordClient
        arguments:
            - { token: '%env(DISCORD_BOT_TOKEN)%' }

    Wohali\OAuth2\Client\Provider\Discord:
        class: Wohali\OAuth2\Client\Provider\Discord
        arguments:
            - { clientId: '%env(DISCORD_CLIENT_ID)%', clientSecret: '%env(DISCORD_CLIENT_SECRET)%', redirectUri: '%env(DISCORD_OAUTH_REDIRECT_URL)%' }

    App\Media\Adapter\AdapterInterface:
        class: App\Media\Adapter\LocalAdapter
        arguments:
            - '%kernel.project_dir%/public/cdn'

    App\Media\WebHandlerInterface:
        class: App\Media\WebHandler
        arguments:
            - '@App\Media\Adapter\AdapterInterface'
            - '%cdns%'

    App\Storage\Snowflake\SnowflakeGeneratorInterface:
        class: App\Storage\Snowflake\RedisGenerator
        arguments:
            - '@Redis'
